In [2]:
import numpy as np
import pandas as pd

In [21]:
data1 = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df1=pd.DataFrame(data1)

In [8]:
# TO KONOW HOW MANY TRUE AND HOW MANY FALSE VALUE 
df1.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [11]:
# TO KONOW HOW MANY TRUE AND HOW MANY FALSE VALUES IN EACH COLUMN
df1.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [12]:
#  TO UDENTIFY WHETHER DATAFRAME HAS NULL VALUES OR NOT
df1.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [26]:
# DROPPING ALL NULL VALUE

# df1.dropna()
df1

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [25]:
# IF NON NULL VALUES IS LESS THAN 2 THEN DELTE THAT ROW
df1.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [27]:
# FILLING THE MISSING DATA

In [28]:
# TO REPLACE/FILL NULL VALUES WITH 0
df1.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [29]:
# TO REPLACE/FILL EACH COLUMN HAVING NULL VALUES WITH PARTIULCAR VALUES
values={'A':0,'B':7,'C':8,'D':10}
df1.fillna(value=values)

     A    B    C     D
0  1.0  7.0  1.0   1.0
1  2.0  2.0  2.0  10.0
2  0.0  3.0  3.0  10.0
3  4.0  4.0  8.0  10.0
4  5.0  5.0  8.0   5.0

In [30]:
# .isna() for checking .dropna() for dropping null values .fillna for fillling null value
# fill column wise and drop is row wise

In [31]:
df1.fillna(df1.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0